; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 469
global g_ImportsGameVersionPostFix64 := ""
=======
global g_ImportsGameVersion64 = 467
global g_ImportsGameVersionPostFix64 = ""
>>>>>>> 6a912e2aab5a830e15b171dcfdef05d0c0bb78d1
